package com.ThimoteoConsultorias.Consulthi.enums;

public enum ExpertiseArea
{
    HIGH_PERFORMANCE_SPORTS,
    PHYSICAL_EDUCATION,
    PHYSIOTHERAPY,
    SPORTS,
    
    BEHAVIORAL_NUTRITION,
    CLINICAL_NUTRITION,
    HEALTH_NUTRITION,
    SPORTS_NUTRITION,
    
    CLINICAL_PSYCHOLOGY,
    EXERCISE_PSYCHOLOGY,
    EDUCACIONAL_PSYCHOLOGY,
    SPORTS_PSYCHOLOGY;
}