FROM maven:3-eclipse-temurin-23

# Instala o Node.js (para o Tailwind)
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

WORKDIR /app

# Copia e instala as dependências do npm
COPY package.json package-lock.json* ./
RUN npm install

# Copia o Maven wrapper
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

COPY src ./src
COPY tailwind.config.js .
COPY start-dev.sh .

# Dá permissão de execução ao script de início
RUN chmod +x start-dev.sh

EXPOSE 8080

ENTRYPOINT ["./start-dev.sh"]